### ISSUE TITLE
New parameter setting to include/exclude ensemble for climr_downscale

### ISSUE THREAD

**Issue by whmacken** [bcgov/climr#263] opened 2024-05-15 17:05 UTC
Currently climr_downscale has a parameter for max_run where zero returns the ensemble only. 
Setting the max_run to higher numbers returns the ensemble plus additional individual GCM runs.
It would be better to allow explicit control in the parameters about whether to return only individual runs, only ensemble, or both.

**Comment by cmahony** [comment] 2024-05-15 17:09
@whmacken, fully agreed. we are planning to overhaul our gcm and run specification options. i'll add this to the list.

**Comment by kdaust** [comment] 2024-08-14 21:28
Closing as duplicate of #155

**Closed by kdaust** 2024-08-14 21:28 UTC
Labels: enhancement, v1.0.0, user
