### ISSUE TITLE
`historic_input_ts` retrieves more years than those asked for?

### ISSUE THREAD

**Issue by CeresBarros** [bcgov/climr#157] opened 2024-01-03 01:25 UTC
I've noticed that `historic_input_ts` is returning layers for years outside the specified range. Is this intended?

```
  dbCon <- data_connect()
  ## smaller example in BC
  xyz <- data.frame(Long = c(-127.70521, -127.62279, -127.56235, -127.7162, 
                             -127.18585, -127.1254, -126.94957, -126.95507),
                    Lat = c(55.3557, 55.38847, 55.28537, 55.25721, 
                            54.88135, 54.65636, 54.6913, 54.61025),
                    Elev = c(291L, 296L, 626L, 377L, 424L, 591L, 723L, 633L),
                    ID = LETTERS[1:8],
                    Zone = c(rep("CWH",3), rep("CDF",5)),
                    Subzone = c("vm1","vm2","vs1",rep("mm",3),"dk","dc"))
  
  thebb <- get_bb(xyz)
  
  histtsout <- historic_input_ts(dbCon, thebb, years = 2017:2022, cache = TRUE)
  unique(sub(".*_", "", names(histtsout[[1]])))
 [1] "1950" "1951" "1952" "1953" "1954" "1955" "1956" "1957" "1958" "1959"
[11] "1960" "1961" "1962" "1963" "1964" "1965" "1966" "1967" "1968" "1969"
[21] "1970" "1971" "1972" "1973" "1974" "1975" "1976" "1977" "1978" "1979"
[31] "1980" "1981" "1982" "1983" "1984" "1985" "1986" "1987" "1988" "1989"
[41] "1990" "1991" "1992" "1993" "1994" "1995" "1996" "1997" "1998" "1999"
[51] "2000" "2001" "2002" "2003" "2004" "2005" "2006" "2007" "2008" "2009"
[61] "2010" "2011" "2012" "2013" "2014" "2015" "2016" "2017" "2018" "2019"
[71] "2020" "2021" "2022"
  
 ```

**Comment by kdaust** [comment] 2024-01-08 22:02
Oh yes I think I know where the issue is. I'll try and fix that asap.

**Comment by CeresBarros** [comment] 2024-01-08 22:58
awesome thanks

**Comment by kdaust** [comment] 2024-02-08 20:26
Fixed in https://github.com/bcgov/climr/commit/5f48e97c3ab7bca35ca87477084cc25c39c98a6c

**Closed by kdaust** 2024-02-08 20:26 UTC
Labels: urgent
